concurrency:
  cancel-in-progress: true
  group: graalvm-${{ github.workflow }}-${{ github.ref }}
env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3 -Dspotless.apply.skip=true
jobs:
  nativetest:
    if: github.repository == 'apache/shardingsphere'
    name: GraalVM - GraalVM CE for JDK ${{ matrix.java-version }} on ${{ matrix.os
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: graalvm/setup-graalvm@v1
      with:
        cache: maven
        distribution: graalvm-community
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Run nativeTest with GraalVM CE for ${{ matrix.java-version }}
      run: ./mvnw -PnativeTestInShardingSphere -T1C -e clean test
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 22.0.1
        os:
        - ubuntu-latest
      max-parallel: 20
    timeout-minutes: 60
name: NativeTest CI - GraalVM Native Image
on:
  repository_dispatch:
    types: trigger-ga___graalvm.yml
