env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3 -Dspotless.apply.skip=true
  RUNS_ON: ubuntu-latest
jobs:
  database-parse:
    if: github.repository == 'apache/shardingsphere'
    name: CI - SQL Parser
    needs: global-environment
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ needs.global-environment.outputs.GLOBAL_CACHE_PREFIX }}-maven-third-party-cache-${{
          github.sha }}
        path: ~/.m2/repository
        restore-keys: '${{ needs.global-environment.outputs.GLOBAL_CACHE_PREFIX }}-maven-third-party-cache-

          ${{ needs.global-environment.outputs.GLOBAL_CACHE_PREFIX }}-maven-third-party-

          '
    - continue-on-error: true
      name: Build Project with Maven
      run: ./mvnw -T1C -B -ntp clean install
    - continue-on-error: true
      name: Run SQL Parser
      run: ./mvnw -nsu -B install -f parser/sql/dialect/${{ matrix.database }}/pom.xml
        -Dsql.parser.external.it.enabled=true
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: sql-report
        path: /tmp/*.csv
    strategy:
      fail-fast: false
      matrix:
        database:
        - mysql
        - postgresql
      max-parallel: 20
    timeout-minutes: 90
  global-environment:
    name: Import Global Environment
    uses: ./.github/workflows/required-reusable.yml
name: Nightly - SQL parser loading from external cases
on:
  repository_dispatch:
    types: trigger-ga___nightly-sql-parser.yml
