concurrency:
  cancel-in-progress: true
  group: check-${{ github.workflow }}-${{ github.ref }}
jobs:
  check-checkstyle:
    if: ${{ needs.global-environment.outputs.GLOBAL_JOB_ENABLED == 'true' }}
    name: Check - CheckStyle
    needs: global-environment
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Run CheckStyle
      run: ./mvnw checkstyle:check -Pcheck -T1C
    timeout-minutes: 10
  check-license:
    if: ${{ needs.global-environment.outputs.GLOBAL_JOB_ENABLED == 'true' }}
    name: Check - License
    needs: global-environment
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Run Apache Rat
      run: ./mvnw apache-rat:check -Pcheck -T1C
    timeout-minutes: 10
  check-spotless:
    if: ${{ needs.global-environment.outputs.GLOBAL_JOB_ENABLED == 'true' }}
    name: Check - Spotless
    needs: global-environment
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Run Spotless
      run: ./mvnw spotless:check -Pcheck -T1C
    timeout-minutes: 10
  global-environment:
    name: Import Global Environment
    uses: ./.github/workflows/required-reusable.yml
name: Required - Check
on:
  repository_dispatch:
    types: trigger-ga___required-check.yml
